# Introduction to NumPy

#### ►NumPy (Numerical Python)is a open-source library widely used in data science,scietific computing,machine learning,data analytics,business analytics,generative ai.It provides powerful data structure and functions that enable efficient numerical operations on large datasets.

In [5]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

In [7]:
import numpy as np   # importing numpy with alias as np 

In [9]:
np.__version__

'1.26.4'

## ARRAY

#### Array is a data structure used to store multiple similar/homogeneous values in a single variable.

-
    All items must be the same data type(all int/all string)
-
    Elements are stored in a adjecent memory location,which makes access fast.
-   We can access elements using an index.
-   Types of arrays:
    -   1D Array- a simple list of elements (single lined array)
    -   2D Array- Array with two dimensions (rows x columns)
    -   ND Array- Array with more than two dimensions
    

- Array Properties :
    - ->a.shape #Return the shape of array (rows x columns)
    - ->a.dtype  #Return the data type (int,float).
    - a.ndim  #Returns the number of dimensions of the array.
    - a.size #Returns the number of elements.  

- Array Creations:
    - np.zeros(rows x columns) # Creates an array of all zeros.
    - np.ones(rows x columns)  # creates an arryay with all ones.
    - np.arange(start,stop,step) #Creates an array with sequenced values.
   

- Array Functions:
    - np.sum()
    - np.mean()
    - np.std()
    - np.max()
    - np.min()
    - np.argmax()
    - np.argmin()

In [22]:
#Creating a list and converting to a array
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [24]:
type(my_list)

list

In [26]:
#converting list to array
#Syntax=np.array(list_name)
arr=np.array(my_list)
print(arr)
type(arr)

[0 1 2 3 4 5]


numpy.ndarray

In [30]:
np.arange(10) 
# .arange()Returns just like range but in array format. here it returns 0-9
#Syntax->np.arange(start,stop,stop)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(10,20)   #Returns the numbers in an array between 10-19

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
np.arange(10,50,5) # It return the array with the numbe s between 10-50 with the step of 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [36]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [38]:
np.arange(10,30,3,4)

TypeError: Cannot interpret '4' as a data type

In [40]:
np.arange(30,10) # It rises a error because the start value should be less than the stop value.

array([], dtype=int32)

In [42]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

#### np.zeros()
###### np.zeros(rows x columns) - creates an array with all zeros

In [46]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [58]:
np.zeros((2,2)) #2d array

array([[0., 0.],
       [0., 0.]])

In [60]:
np.zeros((5,9),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### np.ones(rows x xolumns)
###### np.ones()- creates an array with all ones.

In [65]:
np.ones(3) # created an array with all ones 


array([1., 1., 1.])

In [67]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [69]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])