# Introduction to NumPy


#### ►NumPy (Numerical Python)is a open-source library widely used in data science,scietific computing,machine learning,data analytics,business analytics,generative ai.It provides powerful data structure and functions that enable efficient numerical operations on large datasets.

In [285]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

In [3]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

## ARRAY

#### Array is a data structure used to store multiple similar/homogeneous values in a single variable.

-
    All items must be the same data type(all int/all string)
-
    Elements are stored in a adjecent memory location,which makes access fast.
-   We can access elements using an index.
-   Types of arrays:
    -   1D Array- a simple list of elements (single lined array)
    -   2D Array- Array with two dimensions (rows x columns)
    -   ND Array- Array with more than two dimensions

- Array Properties :
    - ->a.shape #Return the shape of array (rows x columns)
    - ->a.dtype  #Return the data type (int,float).
    - a.ndim  #Returns the number of dimensions of the array.
    - a.size #Returns the number of elements.  

- Array Creations:
    - np.zeros(rows x columns) # Creates an array of all zeros.
    - np.ones(rows x columns)  # creates an arryay with all ones.
    - np.arange(start,stop,step) #Creates an array with sequenced values.
   

- Array Functions:
    - np.sum()
    - np.mean()
    - np.std()
    - np.max()
    - np.min()
    - np.argmax()
    - np.argmin()

In [291]:
#Creating a list and converting to a array
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [9]:
type(my_list)

list

In [53]:
#converting list to array
#Syntax=np.array(list_name)
arr=np.array(my_list)
print(arr)
type(arr)

array([0, 1, 2, 3, 4, 5])

In [15]:
type(arr)

numpy.ndarray

In [19]:
np.arange(10) 
# .arange()Returns just like range but in array format. here it returns 0-9
#Syntax->np.arange(start,stop,stop)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(10,20)  #Returns the numbers in an array between 10-19

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
np.arange(10,50,5) # It return the array with the numbe s between 10-50 with the step of 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [27]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [29]:
np.arange(10,30,3,4)

TypeError: Cannot interpret '4' as a data type

In [31]:
np.arange(30,10) # It rises a error because the start value should be less than the stop value.

array([], dtype=int32)

In [33]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

#### np.zeros()
###### np.zeros(rows x columns) - creates an array with all zeros

In [35]:
np.zeros(3)

array([0., 0., 0.])

In [294]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [ ]:
np.zeros((2,2)) #2d array

In [41]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [45]:
np.zeros((5,3))  #

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [51]:
#Syntax-> np.zeros((row,column))
nd=np.zeros((5,9),dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
#### np.ones(rows x xolumns)
###### np.ones()- creates an array with all ones.

In [53]:
np.ones(3)# created an array with all ones 

array([1., 1., 1.])

In [55]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [61]:
nd1=np.ones((10,10),dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [296]:
#Create an identity matrix.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [298]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Array Manipulation Functions.

In [301]:
# Reshape an array
a1=np.array([1,2,3,4])
print(a1)
a1=a1.reshape(4,1)
print(a1)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [303]:
#Flaten an array -> convert multidimensional array to 1D array
f=np.array([[1,2,3],[4,5,6]])
f=f.ravel()
f

array([1, 2, 3, 4, 5, 6])

In [305]:
#Transpose an array -> it converts rows to column and columns to rows.
t1=np.array([[1,2],[3,4]])
transposed1=t1.transpose()
transposed1

array([[1, 3],
       [2, 4]])

In [307]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2])
print(stacked)

[[1 2]
 [3 4]]


# Mathemetical Function

In [310]:
#Adding a value to each element.
arr=np.array([1,2,3,4])
added=np.add(arr,2) # adding 2 to each element
print(added)

[3 4 5 6]


In [312]:
#Squre each element of the array.
print(arr)
sqrd=np.power(arr,2) # it give the power of each element of the array
print(sqrd)

[1 2 3 4]
[ 1  4  9 16]


In [314]:
#Squre root of each element of the array. -> it return the root values in float type
print(sqrd)
sqrt_val=np.sqrt(sqrd)
print(sqrt_val)

[ 1  4  9 16]
[1. 2. 3. 4.]


In [316]:
#Dot product of two array
print(arr)
print(sqrd)
product=np.dot(arr,sqrd)
print(product)

[1 2 3 4]
[ 1  4  9 16]
100


# Random

In [19]:
randnum=np.random.rand(3,2)
randnum


array([[0.47114531, 0.15197511],
       [0.06032196, 0.75615147],
       [0.35749789, 0.2026877 ]])

In [19]:
randnum=np.random.rand(3,2)
randnum


array([[0.47114531, 0.15197511],
       [0.06032196, 0.75615147],
       [0.35749789, 0.2026877 ]])

In [17]:
randnum=np.random.rand(2)
print(randnum)
randnum=np.random.rand(2)
print(randnum)

randnum=np.random.rand(2)
print(randnum)


[0.79510524 0.71929777]
[0.66068056 0.49468095]
[0.99734952 0.83701034]


In [31]:
np.random.randint(3)

2

In [33]:
np.random.randint(2,10)

5

In [35]:
np.random.randint(2,10,3)

array([8, 6, 5])

In [37]:
np.random.randint(-30,10,10)

array([-21, -29, -30, -24, -16, -20, -18, -16,   9,   9])

In [39]:
np.random.randint(10,40,(10,10))

array([[35, 32, 23, 19, 32, 18, 11, 34, 10, 23],
       [11, 20, 27, 16, 13, 31, 38, 30, 23, 12],
       [19, 31, 33, 30, 20, 16, 21, 38, 15, 26],
       [15, 31, 19, 12, 27, 32, 25, 10, 23, 15],
       [12, 39, 29, 25, 13, 30, 24, 18, 31, 25],
       [10, 24, 23, 14, 37, 18, 38, 28, 12, 39],
       [29, 37, 34, 34, 25, 37, 20, 39, 13, 35],
       [14, 32, 33, 12, 10, 19, 22, 19, 33, 37],
       [20, 34, 14, 17, 18, 16, 18, 36, 15, 18],
       [27, 28, 18, 13, 25, 14, 12, 35, 11, 26]])

In [45]:
m=np.random.randint(10,40,(10,10))
m

array([[11, 18, 16, 10, 20, 26, 23, 30, 16, 39],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35],
       [19, 36, 28, 39, 18, 24, 17, 35, 34, 31],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [29, 31, 29, 23, 16, 32, 34, 17, 26, 37],
       [32, 10, 21, 38, 18, 16, 30, 22, 38, 32],
       [16, 16, 16, 27, 28, 13, 29, 12, 35, 24],
       [26, 32, 31, 25, 22, 39, 22, 38, 38, 15],
       [30, 11, 22, 12, 21, 34, 26, 13, 11, 28],
       [13, 26, 28, 18, 35, 21, 31, 21, 30, 19]])

In [45]:
m=np.random.randint(10,40,(10,10))
m

array([[11, 18, 16, 10, 20, 26, 23, 30, 16, 39],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35],
       [19, 36, 28, 39, 18, 24, 17, 35, 34, 31],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [29, 31, 29, 23, 16, 32, 34, 17, 26, 37],
       [32, 10, 21, 38, 18, 16, 30, 22, 38, 32],
       [16, 16, 16, 27, 28, 13, 29, 12, 35, 24],
       [26, 32, 31, 25, 22, 39, 22, 38, 38, 15],
       [30, 11, 22, 12, 21, 34, 26, 13, 11, 28],
       [13, 26, 28, 18, 35, 21, 31, 21, 30, 19]])

In [55]:
arr

array([0, 1, 2, 3, 4, 5])

In [59]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [63]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [65]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [110]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Slicing in matriix

In [68]:
m

array([[11, 18, 16, 10, 20, 26, 23, 30, 16, 39],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35],
       [19, 36, 28, 39, 18, 24, 17, 35, 34, 31],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [29, 31, 29, 23, 16, 32, 34, 17, 26, 37],
       [32, 10, 21, 38, 18, 16, 30, 22, 38, 32],
       [16, 16, 16, 27, 28, 13, 29, 12, 35, 24],
       [26, 32, 31, 25, 22, 39, 22, 38, 38, 15],
       [30, 11, 22, 12, 21, 34, 26, 13, 11, 28],
       [13, 26, 28, 18, 35, 21, 31, 21, 30, 19]])

In [70]:
b=np.random.randint(10,20,(5,4))
b

array([[18, 18, 12, 19],
       [18, 12, 15, 11],
       [18, 16, 16, 18],
       [18, 10, 17, 12],
       [14, 15, 11, 14]])

In [72]:
b[:]

array([[18, 18, 12, 19],
       [18, 12, 15, 11],
       [18, 16, 16, 18],
       [18, 10, 17, 12],
       [14, 15, 11, 14]])

In [74]:
b[1:4]

array([[18, 12, 15, 11],
       [18, 16, 16, 18],
       [18, 10, 17, 12]])

In [76]:
b[-1:]

array([[14, 15, 11, 14]])

In [78]:
b[:-1]

array([[18, 18, 12, 19],
       [18, 12, 15, 11],
       [18, 16, 16, 18],
       [18, 10, 17, 12]])

In [80]:
b[-2:]

array([[18, 10, 17, 12],
       [14, 15, 11, 14]])

In [82]:
b[1,3]

11

In [84]:
b[1,-1]

11

In [112]:
b[0,2]

12

In [114]:
b[-5,-3]

18

# NumPy Operatioins

In [87]:

#indexing


In [89]:
m

array([[11, 18, 16, 10, 20, 26, 23, 30, 16, 39],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35],
       [19, 36, 28, 39, 18, 24, 17, 35, 34, 31],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [29, 31, 29, 23, 16, 32, 34, 17, 26, 37],
       [32, 10, 21, 38, 18, 16, 30, 22, 38, 32],
       [16, 16, 16, 27, 28, 13, 29, 12, 35, 24],
       [26, 32, 31, 25, 22, 39, 22, 38, 38, 15],
       [30, 11, 22, 12, 21, 34, 26, 13, 11, 28],
       [13, 26, 28, 18, 35, 21, 31, 21, 30, 19]])

In [116]:
id(m)

1707839010736

In [91]:
m[1,5]

32

In [118]:
m[:]

array([[11, 18, 16, 10, 20, 26, 23, 30, 16, 39],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35],
       [19, 36, 28, 39, 18, 24, 17, 35, 34, 31],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [29, 31, 29, 23, 16, 32, 34, 17, 26, 37],
       [32, 10, 21, 38, 18, 16, 30, 22, 38, 32],
       [16, 16, 16, 27, 28, 13, 29, 12, 35, 24],
       [26, 32, 31, 25, 22, 39, 22, 38, 38, 15],
       [30, 11, 22, 12, 21, 34, 26, 13, 11, 28],
       [13, 26, 28, 18, 35, 21, 31, 21, 30, 19]])

In [120]:
m[:4]

array([[11, 18, 16, 10, 20, 26, 23, 30, 16, 39],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35],
       [19, 36, 28, 39, 18, 24, 17, 35, 34, 31],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35]])

In [122]:
m[0:5]

array([[11, 18, 16, 10, 20, 26, 23, 30, 16, 39],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35],
       [19, 36, 28, 39, 18, 24, 17, 35, 34, 31],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [29, 31, 29, 23, 16, 32, 34, 17, 26, 37]])

In [124]:
m[-1:]

array([[13, 26, 28, 18, 35, 21, 31, 21, 30, 19]])

In [126]:
m[:-1]

array([[11, 18, 16, 10, 20, 26, 23, 30, 16, 39],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35],
       [19, 36, 28, 39, 18, 24, 17, 35, 34, 31],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [29, 31, 29, 23, 16, 32, 34, 17, 26, 37],
       [32, 10, 21, 38, 18, 16, 30, 22, 38, 32],
       [16, 16, 16, 27, 28, 13, 29, 12, 35, 24],
       [26, 32, 31, 25, 22, 39, 22, 38, 38, 15],
       [30, 11, 22, 12, 21, 34, 26, 13, 11, 28]])

In [140]:
m[-4:]

array([[16, 16, 16, 27, 28, 13, 29, 12, 35, 24],
       [26, 32, 31, 25, 22, 39, 22, 38, 38, 15],
       [30, 11, 22, 12, 21, 34, 26, 13, 11, 28],
       [13, 26, 28, 18, 35, 21, 31, 21, 30, 19]])

In [142]:
m[::-1]

array([[13, 26, 28, 18, 35, 21, 31, 21, 30, 19],
       [30, 11, 22, 12, 21, 34, 26, 13, 11, 28],
       [26, 32, 31, 25, 22, 39, 22, 38, 38, 15],
       [16, 16, 16, 27, 28, 13, 29, 12, 35, 24],
       [32, 10, 21, 38, 18, 16, 30, 22, 38, 32],
       [29, 31, 29, 23, 16, 32, 34, 17, 26, 37],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [19, 36, 28, 39, 18, 24, 17, 35, 34, 31],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35],
       [11, 18, 16, 10, 20, 26, 23, 30, 16, 39]])

In [158]:
#Add operation->add values to the elements of the array

arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
added=np.add(arr1,arr2)
print(added)

arr1=np.add(arr1,2)  #-> add 2 to the each element of the array
print(arr1)

[ 6  8 10 12]
[3 4 5 6]


In [168]:
#Substract operation-> substract values from each element of the array
print(arr1)
print(arr2)
sub=np.subtract(arr1,arr2)
print(sub)

print(np.subtract(arr1,2)) # it subtract 2 from each element of the array.


[3 4 5 6]
[5 6 7 8]
[-2 -2 -2 -2]
[1 2 3 4]


In [172]:
#Multiply -> it multiply each element of the array with a number
print(arr1)
print(arr2)
multiply=np.multiply(arr1,arr2)
print(multiply)

print(np.multiply(arr1,2))


[3 4 5 6]
[5 6 7 8]
[15 24 35 48]
[ 6  8 10 12]


In [178]:
#divide -> divide left side each element with right side
print(arr1)
print(arr2)
div=np.divide(arr2,arr1)
print(div)

[3 4 5 6]
[5 6 7 8]
[1.66666667 1.5        1.4        1.33333333]


In [184]:
#mean-> it returns the average value of the array.
print(arr1)
mean=arr1.mean()
print(mean)
arr1.max()

[3 4 5 6]
4.5


6

In [188]:
#max()-> max function returns the highest value of the array.
print(arr1)
print(arr1.min())


[3 4 5 6]
3


In [194]:
#sum() -> sum returns the sum of the each element of the array.
print(arr1)
arr1.sum()


[3 4 5 6]


18

In [202]:
#average() ->returns the average float value
print(np.average(arr2))


6.5


In [212]:
#Median-> return the middle value if present if not it return the average value of midddle teo element.
print(arr1)
print(np.median(arr1))

s1=np.array([10,20,30,40,50])
print(s1)
np.median(s1)

[3 4 5 6]
4.5
[10 20 30 40 50]


30.0

In [218]:
#Square-> return the square of each value
print(s1)
np.square(s1)

[10 20 30 40 50]


array([ 100,  400,  900, 1600, 2500])

In [222]:
#sqrt -> returns the squarerooted value of each element of the array
s1=np.sqrt(s1)
print(s1)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [224]:
#Power-> return the exponential values of each value of the array
print(s1)
np.power(s1,2)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


array([10., 20., 30., 40., 50.])

In [93]:
row=4
col=5

In [226]:
m

array([[11, 18, 16, 10, 20, 26, 23, 30, 16, 39],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35],
       [19, 36, 28, 39, 18, 24, 17, 35, 34, 31],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [29, 31, 29, 23, 16, 32, 34, 17, 26, 37],
       [32, 10, 21, 38, 18, 16, 30, 22, 38, 32],
       [16, 16, 16, 27, 28, 13, 29, 12, 35, 24],
       [26, 32, 31, 25, 22, 39, 22, 38, 38, 15],
       [30, 11, 22, 12, 21, 34, 26, 13, 11, 28],
       [13, 26, 28, 18, 35, 21, 31, 21, 30, 19]])

In [230]:
np.shape(m)

(10, 10)

In [232]:
m[5]

array([32, 10, 21, 38, 18, 16, 30, 22, 38, 32])

In [95]:
m[row,col]

32

In [97]:
m[row] # prints rows


array([29, 31, 29, 23, 16, 32, 34, 17, 26, 37])

In [99]:
m[:,col]

array([26, 32, 24, 32, 32, 16, 13, 39, 34, 21])

In [237]:
m[:,3] #prints the 3th column

array([10, 20, 39, 12, 23, 38, 27, 25, 12, 18])

In [241]:
m[:]

array([[11, 18, 16, 10, 20, 26, 23, 30, 16, 39],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35],
       [19, 36, 28, 39, 18, 24, 17, 35, 34, 31],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [29, 31, 29, 23, 16, 32, 34, 17, 26, 37],
       [32, 10, 21, 38, 18, 16, 30, 22, 38, 32],
       [16, 16, 16, 27, 28, 13, 29, 12, 35, 24],
       [26, 32, 31, 25, 22, 39, 22, 38, 38, 15],
       [30, 11, 22, 12, 21, 34, 26, 13, 11, 28],
       [13, 26, 28, 18, 35, 21, 31, 21, 30, 19]])

In [239]:
m[::-1] #reverse the matrix

array([[13, 26, 28, 18, 35, 21, 31, 21, 30, 19],
       [30, 11, 22, 12, 21, 34, 26, 13, 11, 28],
       [26, 32, 31, 25, 22, 39, 22, 38, 38, 15],
       [16, 16, 16, 27, 28, 13, 29, 12, 35, 24],
       [32, 10, 21, 38, 18, 16, 30, 22, 38, 32],
       [29, 31, 29, 23, 16, 32, 34, 17, 26, 37],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [19, 36, 28, 39, 18, 24, 17, 35, 34, 31],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35],
       [11, 18, 16, 10, 20, 26, 23, 30, 16, 39]])

In [245]:
m[::-2] #it reverse a sequence with skip of one row

array([[13, 26, 28, 18, 35, 21, 31, 21, 30, 19],
       [26, 32, 31, 25, 22, 39, 22, 38, 38, 15],
       [32, 10, 21, 38, 18, 16, 30, 22, 38, 32],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [12, 37, 21, 20, 32, 32, 23, 14, 11, 35]])

In [247]:
m[::-3]

array([[13, 26, 28, 18, 35, 21, 31, 21, 30, 19],
       [16, 16, 16, 27, 28, 13, 29, 12, 35, 24],
       [12, 28, 10, 12, 28, 32, 10, 26, 10, 35],
       [11, 18, 16, 10, 20, 26, 23, 30, 16, 39]])

In [103]:
m[1:6,1:4]

array([[37, 21, 20],
       [36, 28, 39],
       [28, 10, 12],
       [31, 29, 23],
       [10, 21, 38]])

In [249]:
m[2:6,2:3] #it vertically slice a column 2 across row 2-5

array([[28],
       [10],
       [29],
       [21]])

# Masking

In [267]:
mat=np.arange(10,100).reshape(10,10)
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [271]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [275]:
mat<50


array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [273]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [277]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [279]:
mat[mat==50]

array([50])

In [281]:
mat[mat!=50
]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])