# Introduction to NumPy

#### ►NumPy (Numerical Python)is a open-source library widely used in data science,scietific computing,machine learning,data analytics,business analytics,generative ai.It provides powerful data structure and functions that enable efficient numerical operations on large datasets.

In [5]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

In [4]:
import numpy as np   # importing numpy with alias as np 

In [9]:
np.__version__

'1.26.4'

## ARRAY

#### Array is a data structure used to store multiple similar/homogeneous values in a single variable.

-
    All items must be the same data type(all int/all string)
-
    Elements are stored in a adjecent memory location,which makes access fast.
-   We can access elements using an index.
-   Types of arrays:
    -   1D Array- a simple list of elements (single lined array)
    -   2D Array- Array with two dimensions (rows x columns)
    -   ND Array- Array with more than two dimensions
    

- Array Properties :
    - ->a.shape #Return the shape of array (rows x columns)
    - ->a.dtype  #Return the data type (int,float).
    - a.ndim  #Returns the number of dimensions of the array.
    - a.size #Returns the number of elements.  

- Array Creations:
    - np.zeros(rows x columns) # Creates an array of all zeros.
    - np.ones(rows x columns)  # creates an arryay with all ones.
    - np.arange(start,stop,step) #Creates an array with sequenced values.
   

- Array Functions:
    - np.sum()
    - np.mean()
    - np.std()
    - np.max()
    - np.min()
    - np.argmax()
    - np.argmin()

In [22]:
#Creating a list and converting to a array
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [24]:
type(my_list)

list

In [26]:
#converting list to array
#Syntax=np.array(list_name)
arr=np.array(my_list)
print(arr)
type(arr)

[0 1 2 3 4 5]


numpy.ndarray

In [30]:
np.arange(10) 
# .arange()Returns just like range but in array format. here it returns 0-9
#Syntax->np.arange(start,stop,stop)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(10,20)   #Returns the numbers in an array between 10-19

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
np.arange(10,50,5) # It return the array with the numbe s between 10-50 with the step of 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [36]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [38]:
np.arange(10,30,3,4)

TypeError: Cannot interpret '4' as a data type

In [40]:
np.arange(30,10) # It rises a error because the start value should be less than the stop value.

array([], dtype=int32)

In [42]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

#### np.zeros()
###### np.zeros(rows x columns) - creates an array with all zeros

In [46]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [58]:
np.zeros((2,2)) #2d array

array([[0., 0.],
       [0., 0.]])

In [60]:
np.zeros((5,9),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### np.ones(rows x xolumns)
###### np.ones()- creates an array with all ones.

In [65]:
np.ones(3) # created an array with all ones 


array([1., 1., 1.])

In [67]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [69]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [6]:
#Create an identity matrix.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Array Manipulation Functions.

In [15]:
# Reshape an array
a1=np.array([1,2,3,4])
print(a1)
a1=a1.reshape(4,1)
print(a1)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [25]:
#Flaten an array -> convert multidimensional array to 1D array
f=np.array([[1,2,3],[4,5,6]])
f=f.ravel()
f

array([1, 2, 3, 4, 5, 6])

In [27]:
#Transpose an array -> it converts rows to column and columns to rows.
t1=np.array([[1,2],[3,4]])
transposed1=t1.transpose()
transposed1

array([[1, 3],
       [2, 4]])

In [29]:
#Stack array vertically -> stack a and b vertically
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2])
print(stacked)

[[1 2]
 [3 4]]


# Mathemetical Function

In [34]:
#Adding a value to each element.
arr=np.array([1,2,3,4])
added=np.add(arr,2) # adding 2 to each element
print(added)

[3 4 5 6]


In [36]:
#Squre each element of the array.
print(arr)
sqrd=np.power(arr,2) # it give the power of each element of the array
print(sqrd)

[1 2 3 4]
[ 1  4  9 16]


In [42]:
#Squre root of each element of the array. -> it return the root values in float type
print(sqrd)
sqrt_val=np.sqrt(sqrd)
print(sqrt_val)

[ 1  4  9 16]
[1. 2. 3. 4.]


In [46]:
#Dot product of two array
print(arr)
print(sqrd)
product=np.dot(arr,sqrd)
print(product)

[1 2 3 4]
[ 1  4  9 16]
100


# Statistical Function

#### Statistical function are operations or algorithm used to analyze and interpret data.

In [50]:
#Mean() -> calculates the average value of the elements
s=np.array([1,2,3,6,4,5])
mean=s.mean()
print(mean)

3.5


In [ ]:
#std- standard division of an array


In [52]:
# Random 


In [54]:
randnum=np.random.rand(2)
print(randnum)
randnum=np.random.rand(2)
print(randnum)

randnum=np.random.rand(2)
print(randnum)

[0.72617711 0.22940992]
[0.20030132 0.70452863]
[0.14715409 0.96352886]


In [56]:
np.random.randint(3)

1

In [58]:
np.random.randint(2,10)

7

In [60]:
np.random.randint(2,10,3)

array([9, 2, 6])

In [62]:
np.random.randint(-30,10,10)

array([-11, -29, -23,  -3,  -2,  -2,  -2, -26, -27,   7])

In [64]:
np.random.randint(10,40,(10,10))

array([[19, 20, 32, 39, 20, 27, 24, 22, 24, 16],
       [14, 38, 38, 21, 28, 20, 13, 22, 36, 39],
       [17, 26, 24, 28, 18, 35, 11, 35, 15, 25],
       [36, 37, 38, 17, 39, 33, 15, 25, 28, 27],
       [37, 37, 23, 25, 28, 32, 10, 36, 12, 11],
       [27, 37, 22, 17, 14, 29, 21, 25, 30, 31],
       [33, 26, 23, 12, 13, 30, 15, 34, 33, 19],
       [32, 10, 17, 20, 31, 21, 25, 16, 18, 30],
       [39, 37, 17, 18, 32, 36, 20, 22, 30, 25],
       [31, 18, 10, 28, 28, 18, 21, 16, 10, 26]])

In [70]:
m=np.random.randint(10,40,(10,10))
m

array([[10, 20, 26, 23, 14, 12, 27, 19, 35, 14],
       [33, 21, 37, 17, 25, 24, 20, 20, 14, 15],
       [11, 34, 19, 34, 15, 35, 15, 16, 22, 27],
       [26, 31, 35, 36, 37, 14, 14, 37, 30, 30],
       [17, 13, 16, 34, 20, 18, 20, 30, 33, 37],
       [35, 39, 32, 36, 28, 37, 17, 27, 23, 15],
       [39, 26, 13, 20, 20, 38, 10, 20, 31, 33],
       [13, 33, 21, 31, 28, 26, 31, 14, 28, 28],
       [11, 23, 34, 13, 27, 12, 23, 25, 15, 38],
       [24, 32, 25, 30, 28, 23, 15, 22, 22, 36]])

In [72]:
m=np.random.randint(10,40,(10,10))
m

array([[22, 24, 26, 33, 14, 12, 15, 17, 36, 18],
       [36, 38, 16, 26, 26, 28, 31, 15, 26, 25],
       [30, 17, 32, 25, 28, 19, 39, 12, 23, 38],
       [35, 22, 19, 25, 10, 39, 38, 14, 21, 36],
       [12, 38, 11, 32, 26, 36, 29, 22, 23, 18],
       [28, 28, 32, 23, 16, 30, 39, 22, 25, 30],
       [29, 16, 24, 37, 19, 25, 24, 34, 28, 18],
       [12, 20, 20, 31, 14, 37, 25, 36, 38, 26],
       [21, 34, 18, 37, 26, 13, 15, 14, 39, 19],
       [31, 35, 18, 23, 17, 18, 16, 22, 22, 13]])

In [84]:
arr=np.array([1,2,3,4,5,6])

In [86]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
arr.reshape(3,3) # if you reshape a array you have to check it have the same value to the reshaped matrix

ValueError: cannot reshape array of size 6 into shape (3,3)

In [92]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [94]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])